import { ProductFeature, Project } from '../App';
import { Dialog, DialogContent, DialogHeader, DialogTitle } from './ui/dialog';
import { Button } from './ui/button';
import { FileText, Copy, Check, FileUp, BookOpen } from 'lucide-react';
import { useState } from 'react';
import { toast } from 'sonner@2.0.3';
import * as api from '../utils/api';

interface ProjectDocumentationPanelProps {
  open: boolean;
  onOpenChange: (open: boolean) => void;
  project: Project;
  features: ProductFeature[];
}

export function ProjectDocumentationPanel({
  open,
  onOpenChange,
  project,
  features,
}: ProjectDocumentationPanelProps) {
  const [copied, setCopied] = useState(false);
  const [isGenerating, setIsGenerating] = useState(false);

  const usedFeatures = features.filter(f => project.featuresUsed.includes(f.id));
  const deployedCount = project.deployedFeatures.length;
  const totalCount = project.featuresUsed.length;

  const documentationText = `Project Documentation

Enabled Products:
${usedFeatures.map(f => `✓ ${f.name}`).join('\n')}

Status:
${deployedCount} / ${totalCount} features deployed

Actions:
[ Generate User Manual ]
[ Upload Supporting Docs ] (optional)`;

  const handleCopy = () => {
    navigator.clipboard.writeText(documentationText);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handleGenerateManual = async () => {
    setIsGenerating(true);
    try {
      // Generate user manual content as HTML
      const currentDate = new Date().toLocaleDateString('en-US', {
        year: 'numeric',
        month: 'long',
        day: 'numeric'
      });
      
      const htmlContent = `
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <title>${project.name} - User Manual</title>
  <style>
    body { font-family: Arial, sans-serif; max-width: 800px; margin: 0 auto; padding: 40px; color: #333; }
    h1 { color: #1a1a2e; border-bottom: 2px solid #6366f1; padding-bottom: 10px; }
    h2 { color: #4f46e5; margin-top: 30px; }
    .meta { color: #666; font-size: 14px; margin-bottom: 30px; }
    .feature-list { list-style: none; padding: 0; }
    .feature-list li { padding: 10px 0; border-bottom: 1px solid #eee; }
    .feature-list li:before { content: "✓"; color: #22c55e; margin-right: 10px; font-weight: bold; }
    .status { background: #f0f9ff; padding: 15px; border-radius: 8px; margin: 20px 0; }
    .status-label { font-weight: bold; color: #0369a1; }
    table { width: 100%; border-collapse: collapse; margin: 20px 0; }
    th, td { padding: 12px; text-align: left; border-bottom: 1px solid #ddd; }
    th { background: #f8fafc; font-weight: 600; }
    .footer { margin-top: 50px; padding-top: 20px; border-top: 1px solid #eee; color: #666; font-size: 12px; }
  </style>
</head>
<body>
  <h1>${project.name}</h1>
  <div class="meta">
    <p><strong>Generated:</strong> ${currentDate}</p>
    <p><strong>Project ID:</strong> ${project.id}</p>
  </div>
  
  <h2>Overview</h2>
  <p>This document provides an overview of the enabled products and deployment status for ${project.name}.</p>
  
  <h2>Enabled Products</h2>
  <ul class="feature-list">
    ${usedFeatures.map(f => `<li>${f.name}</li>`).join('\n    ')}
  </ul>
  
  <h2>Deployment Status</h2>
  <div class="status">
    <span class="status-label">Features Deployed:</span> ${deployedCount} / ${totalCount}
  </div>
  
  <h2>Feature Details</h2>
  <table>
    <thead>
      <tr>
        <th>Feature</th>
        <th>Status</th>
      </tr>
    </thead>
    <tbody>
      ${usedFeatures.map(f => `
      <tr>
        <td>${f.name}</td>
        <td>${project.deployedFeatures.includes(f.id) ? '✓ Deployed' : 'Pending'}</td>
      </tr>`).join('')}
    </tbody>
  </table>
  
  <div class="footer">
    <p>This user manual was auto-generated by the Product Project Management Board.</p>
  </div>
</body>
</html>`;

      // Create and download the HTML file
      const blob = new Blob([htmlContent], { type: 'text/html' });
      const objectUrl = window.URL.createObjectURL(blob);
      const anchor = document.createElement('a');
      anchor.href = objectUrl;
      anchor.download = `${project.name.replace(/[^a-z0-9-_]+/gi, '-')}-user-manual.html`;
      document.body.appendChild(anchor);
      anchor.click();
      anchor.remove();
      window.URL.revokeObjectURL(objectUrl);

      toast.success('User manual downloaded', { description: project.name });
    } catch (error) {
      const message = error instanceof Error ? error.message : 'Failed to generate manual';
      toast.error('Generate User Manual failed', {
        description: message,
      });
    } finally {
      setIsGenerating(false);
    }
  };

  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
      <DialogContent className="max-w-2xl max-h-[80vh] overflow-y-auto">
        <DialogHeader>
          <DialogTitle className="flex items-center gap-2">
            <FileText className="size-5 text-purple-600" />
            Project Documentation
          </DialogTitle>
        </DialogHeader>

        <div className="space-y-6">
          <div className="relative">
            <div className="absolute top-3 right-3">
              <Button
                variant="ghost"
                size="sm"
                onClick={handleCopy}
                className="flex items-center gap-1 text-slate-500 hover:text-slate-400"
              >
                {copied ? (
                  <>
                    <Check className="size-4" />
                    Copied
                  </>
                ) : (
                  <>
                    <Copy className="size-4" />
                    Copy
                  </>
                )}
              </Button>
            </div>

            <div className="bg-slate-900 p-6 rounded-lg font-mono text-sm space-y-4">
              <div>
                <h3 className="text-lg font-semibold mb-3 text-white">{project.name}</h3>
              </div>

              <div>
                <div className="text-slate-500 mb-2">Enabled Products:</div>
                <div className="space-y-1 pl-2">
                  {usedFeatures.map(feature => (
                    <div key={feature.id} className="flex items-start gap-2">
                      <span style={{ color: '#4ade80' }}>✓</span>
                      <span className="text-white">{feature.name}</span>
                    </div>
                  ))}
                </div>
              </div>

              <div>
                <div className="text-slate-500 mb-2">Status:</div>
                <div className="pl-2 text-white">
                  {deployedCount} / {totalCount} features deployed
                </div>
              </div>

              <div>
                <div className="text-slate-500 mb-2">Actions:</div>
                <div className="space-y-1 pl-2">
                  <div className="text-white">[ Generate User Manual ]</div>
                  <div className="text-white">[ Upload Supporting Docs ] <span className="text-slate-500">(optional)</span></div>
                </div>
              </div>
            </div>
          </div>

          <div className="flex flex-col gap-3 pt-2">
            <Button
              className="w-full justify-start gap-2 h-auto py-4"
              variant="outline"
              onClick={handleGenerateManual}
              disabled={isGenerating}
            >
              <BookOpen className="size-5" />
              <div className="flex flex-col items-start">
                <span className="font-semibold">
                  {isGenerating ? 'Generating User Manual...' : 'Generate User Manual'}
                </span>
                <span className="text-sm text-slate-500 font-normal">
                  Auto-generate documentation based on enabled features
                </span>
              </div>
            </Button>

            <Button
              className="w-full justify-start gap-2 h-auto py-4"
              variant="outline"
            >
              <FileUp className="size-5" />
              <div className="flex flex-col items-start">
                <span className="font-semibold">Upload Supporting Docs</span>
                <span className="text-sm text-slate-500 font-normal">
                  Add additional documentation files (optional)
                </span>
              </div>
            </Button>
          </div>

          {(project as any).documentationUrl && (
            <div className="pt-4 border-t">
              <div className="text-sm text-slate-600 mb-2">External Documentation:</div>
              <a
                href={(project as any).documentationUrl}
                target="_blank"
                rel="noopener noreferrer"
                className="text-purple-600 hover:underline text-sm break-all"
              >
                {(project as any).documentationUrl}
              </a>
            </div>
          )}
        </div>
      </DialogContent>
    </Dialog>
  );
}
